export default [
    {
        _id: "Q1-RS101",
        name: "Rocket Propulsion Quiz 1",
        type: "Graded Quiz",
        group: "QUIZZES",
        shuffle: true,
        timed: true,
        minutes: "20",
        multiple_attempts: false,
        attempts_allowed: "1",
        due_date: "",
        assign_to: "",
        available_date: "",
        until_date: "",
        points: "100",
        show_correct_answers: false,
        one_question_at_a_time: true,
        lock_questions: false,
        webcam_required: false,
        access_code: "",
        course: "RS101",
        description: "This course provides an in-depth study of the fundamentals of rocket propulsion, covering topics such as propulsion theory, engine types, fuel chemistry, and the practical applications of rocket technology. Designed for students with a strong background in physics and engineering, the course includes both theoretical instruction and hands-on laboratory work",
        questions: [
            {
                _id: "Q1-RS101-Question1",
                title: "Q1-RS101-Question1",
                q_type: "Multiple Choice",
                q_points: "10",
                q_description: "What is a rocket?",
                quiz: "Q1-RS101",
                answers: [
                    { answer: "A food", correct: false },
                    { answer: "A toy", correct: false },
                    { answer: "A machine", correct: true },
                    { answer: "A weapon", correct: false }
                ]
            },
            {
                _id: "Q1-RS101-Question2",
                title: "Q1-RS101-Question2",
                q_type: "True/False",
                q_points: "10",
                q_description: "A Rocket is a Machine",
                quiz: "Q1-RS101",
                answers: [
                    { answer: "True", correct: true },
                    { answer: "False", correct: false },
                ]
            },
            {
                _id: "Q1-RS101-Question3",
                title: "Q1-RS101-Question3",
                q_type: "Fill In The Blank",
                q_points: "10",
                q_description: "A Rocket is a _______",
                quiz: "Q1-RS101",
                answers: [
                    { answer: "A Machine", correct: true },
                    { answer: "A Scientific Creation", correct: true },
                    { answer: "A Work of Art", correct: true },
                ]
            },
        ]
    },
    {
        _id: "Q2-RS101",
        name: "Rocket Propulsion Quiz 2",
        type: "Graded Quiz",
        group: "QUIZZES",
        shuffle: true,
        timed: true,
        minutes: "20",
        multiple_attempts: false,
        attempts_allowed: "1",
        due_date: "",
        assign_date: "",
        available_date: "",
        until_date: "",
        points: "100",
        show_correct_answers: false,
        one_question_at_a_time: true,
        lock_questions: false,
        webcam_required: false,
        access_code: "",
        course: "RS101",
        description: "This course provides an in-depth study of the fundamentals of rocket propulsion, covering topics such as propulsion theory, engine types, fuel chemistry, and the practical applications of rocket technology. Designed for students with a strong background in physics and engineering, the course includes both theoretical instruction and hands-on laboratory work",
        questions: [
            {
                _id: "Q1-RS101-Question1",
                title: "Q1-RS101-Question1",
                q_type: "Multiple Choice",
                q_points: "10",
                q_description: "What is a rocket?",
                quiz: "Q1-RS101",
                answers: [
                    { answer: "A subject", correct: true },
                    { answer: "A government office", correct: false },
                    { answer: "An animal", correct: true },
                    { answer: "A fruit", correct: false }
                ]
            },
            {
                _id: "Q1-RS101-Question2",
                title: "Q1-RS101-Question2",
                q_type: "True/False",
                q_points: "10",
                q_description: "A Rocket is a fruit",
                quiz: "Q1-RS101",
                answers: [
                    { answer: "True", correct: false },
                    { answer: "False", correct: true },
                ]
            },
            {
                _id: "Q1-RS101-Question3",
                title: "Q1-RS101-Question3",
                q_type: "Fill In The Blank",
                q_points: "10",
                q_description: "Rockes are used by _______",
                quiz: "Q1-RS101",
                answers: [
                    { answer: "astronauts", correct: true },
                    { answer: "government agencies", correct: true },
                    { answer: "explorers", correct: true },
                ]
            },
        ]
    },
    // {
    //     _id: "Q3-RS101",
    //     name: "Rocket Propulsion Quiz 3",
    //     type: "Graded Quiz",
    //     group: "QUIZZES",
    //     shuffle: "Yes",
    //     timed: "Yes",
    //     minutes: "20",
    //     multiple_attempts: "No",
    //     attempts_allowed: "1",
    //     due_date: "",
    //     assign_date: "",
    //     available_date: "",
    //     until_date: "",
    //     points: "100",
    //     show_correct_answers: "No",
    //     one_question_at_a_time: "Yes",
    //     lock_questions: "No",
    //     webcam_required: "No",
    //     access_code: "",
    //     course: "RS101",
    //     description: "This course provides an in-depth study of the fundamentals of rocket propulsion, covering topics such as propulsion theory, engine types, fuel chemistry, and the practical applications of rocket technology. Designed for students with a strong background in physics and engineering, the course includes both theoretical instruction and hands-on laboratory work"
    // },
    // {
    //     _id: "Q1-RS102",
    //     name: "Aerodynamics Quiz 1",
    //     type: "Graded Quiz",
    //     group: "QUIZZES",
    //     shuffle: "Yes",
    //     timed: "Yes",
    //     minutes: "20",
    //     multiple_attempts: "No",
    //     attempts_allowed: "1",
    //     due_date: "",
    //     assign_date: "",
    //     available_date: "",
    //     until_date: "",
    //     points: "100",
    //     show_correct_answers: "No",
    //     one_question_at_a_time: "Yes",
    //     lock_questions: "No",
    //     webcam_required: "No",
    //     access_code: "",
    //     course: "RS102",
    //     description: "This course offers a comprehensive exploration of aerodynamics, focusing on the principles and applications of airflow and its effects on flying objects. Topics include fluid dynamics, airfoil design, lift and drag forces, and the aerodynamic considerations in aircraft design. The course blends theoretical learning with practical applications, suitable for students pursuing a career in aeronautics or astronautics engineering."
    // },
    // {
    //     _id: "Q2-RS102",
    //     name: "Aerodynamics Quiz 2",
    //     type: "Graded Quiz",
    //     group: "QUIZZES",
    //     shuffle: "Yes",
    //     timed: "Yes",
    //     minutes: "20",
    //     multiple_attempts: "No",
    //     attempts_allowed: "1",
    //     due_date: "",
    //     assign_date: "",
    //     available_date: "",
    //     until_date: "",
    //     points: "100",
    //     show_correct_answers: "No",
    //     one_question_at_a_time: "Yes",
    //     lock_questions: "No",
    //     webcam_required: "No",
    //     access_code: "",
    //     course: "RS102",
    //     description: "This course offers a comprehensive exploration of aerodynamics, focusing on the principles and applications of airflow and its effects on flying objects. Topics include fluid dynamics, airfoil design, lift and drag forces, and the aerodynamic considerations in aircraft design. The course blends theoretical learning with practical applications, suitable for students pursuing a career in aeronautics or astronautics engineering."
    // },
    // {
    //     _id: "Q3-RS102",
    //     name: "Aerodynamics Quiz 3",
    //     type: "Graded Quiz",
    //     group: "QUIZZES",
    //     shuffle: "Yes",
    //     timed: "Yes",
    //     minutes: "20",
    //     multiple_attempts: "No",
    //     attempts_allowed: "1",
    //     due_date: "",
    //     assign_date: "",
    //     available_date: "",
    //     until_date: "",
    //     points: "100",
    //     show_correct_answers: "No",
    //     one_question_at_a_time: "Yes",
    //     lock_questions: "No",
    //     webcam_required: "No",
    //     access_code: "",
    //     course: "RS102",
    //     description: "This course offers a comprehensive exploration of aerodynamics, focusing on the principles and applications of airflow and its effects on flying objects. Topics include fluid dynamics, airfoil design, lift and drag forces, and the aerodynamic considerations in aircraft design. The course blends theoretical learning with practical applications, suitable for students pursuing a career in aeronautics or astronautics engineering."
    // },
    // {
    //     _id: "Q1-RS103",
    //     name: "Spacecraft Design Quiz 1",
    //     type: "Graded Quiz",
    //     group: "QUIZZES",
    //     shuffle: "Yes",
    //     timed: "Yes",
    //     minutes: "20",
    //     multiple_attempts: "No",
    //     attempts_allowed: "1",
    //     due_date: "",
    //     assign_date: "",
    //     available_date: "",
    //     until_date: "",
    //     points: "100",
    //     show_correct_answers: "No",
    //     one_question_at_a_time: "Yes",
    //     lock_questions: "No",
    //     webcam_required: "No",
    //     access_code: "",
    //     course: "RS103",
    //     description: "This course delves into the principles and practices of spacecraft design, offering students a detailed understanding of the engineering and technology behind spacecraft systems. Key topics include spacecraft structure, propulsion, power systems, thermal control, and payload integration. Emphasizing both theoretical concepts and practical skills, the course prepares students for careers in the space industry, with a focus on innovative design and problem-solving in the context of current and future space missions"
    // },
    // {
    //     _id: "Q2-RS103",
    //     name: "Spacecraft Design Quiz 2",
    //     type: "Graded Quiz",
    //     group: "QUIZZES",
    //     shuffle: "Yes",
    //     timed: "Yes",
    //     minutes: "20",
    //     multiple_attempts: "No",
    //     attempts_allowed: "1",
    //     due_date: "",
    //     assign_date: "",
    //     available_date: "",
    //     until_date: "",
    //     points: "100",
    //     show_correct_answers: "No",
    //     one_question_at_a_time: "Yes",
    //     lock_questions: "No",
    //     webcam_required: "No",
    //     access_code: "",
    //     course: "RS103",
    //     description: "This course delves into the principles and practices of spacecraft design, offering students a detailed understanding of the engineering and technology behind spacecraft systems. Key topics include spacecraft structure, propulsion, power systems, thermal control, and payload integration. Emphasizing both theoretical concepts and practical skills, the course prepares students for careers in the space industry, with a focus on innovative design and problem-solving in the context of current and future space missions"
    // },
    // {
    //     _id: "Q3-RS103",
    //     name: "Spacecraft Design Quiz 3",
    //     type: "Graded Quiz",
    //     group: "QUIZZES",
    //     shuffle: "Yes",
    //     timed: "Yes",
    //     minutes: "20",
    //     multiple_attempts: "No",
    //     attempts_allowed: "1",
    //     due_date: "",
    //     assign_date: "",
    //     available_date: "",
    //     until_date: "",
    //     points: "100",
    //     show_correct_answers: "No",
    //     one_question_at_a_time: "Yes",
    //     lock_questions: "No",
    //     webcam_required: "No",
    //     access_code: "",
    //     course: "RS103",
    //     description: "This course delves into the principles and practices of spacecraft design, offering students a detailed understanding of the engineering and technology behind spacecraft systems. Key topics include spacecraft structure, propulsion, power systems, thermal control, and payload integration. Emphasizing both theoretical concepts and practical skills, the course prepares students for careers in the space industry, with a focus on innovative design and problem-solving in the context of current and future space missions"
    // },
]